apiVersion: batch/v1
kind: Job
metadata:
  name: database-setup
spec:
  template:
    metadata:
      name: database-setup
    spec:
      containers:
      - name: database-setup
        image: dougg/taiga-back
        imagePullPolicy: IfNotPresent
        command: ["./regenerate.sh", "-y"]
      restartPolicy: OnFailure
